# Generated by Django 4.2 on 2026-01-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_issuer', models.CharField(choices=[('hdfc', 'HDFC'), ('icici', 'ICICI'), ('axis', 'Axis'), ('sbi', 'SBI'), ('yes', 'Yes Bank'), ('kotak', 'Kotak'), ('amex', 'American Express')], max_length=50)),
                ('features', models.TextField(help_text='Features of the credit card, comma separated')),
                ('available_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['card_issuer', 'card_name'],
            },
        ),
    ]
